language: r
sudo: false
cache: packages
matrix:
  include:
  - os: linux
    dist: trusty
    sudo: required
    env: DRAT_DEPLOY=true
  - os: osx
    osx_image: xcode11.3
  - os: osx
    osx_image: xcode10.3
  - os: osx
    osx_image: xcode9.4
r_packages:
- covr
- drat
r_github_packages:
- cloudyr/travisci
after_success:
- R -q -e 'library("covr");codecov()'
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && test
  $DRAT_DEPLOY == "true" && bash drat.sh
- R -q -e "travisci::restart_last_build('cloudyr/awspack')"
env:
  global:
    - secure: AXrCYGXrdVPHO7pZWVpxey55XjBNAM13XMQ7C/SetTjSAmDzaJol5ExOBRNSEvTjiLm9t9rk7zmNZY3U6GdOzLGctS7R5OK6iR8WInu8vC84dhk0G+kbdMQoDTVp+Rf+uLF+I33a174JXKIGJXBXT675e2qExroTfMhGTgxQI56IKiA8WhZMdM1s7hSpmiPehdkmEEFHuWQL7hkunDknd62SbWKjIpoxCxgWPrdtEJFBjYEXQFmc3gvHZibvpBex0xg2QORUoOWe8s8AXw+v+8eC7vBQ/RbX1lwrczF4w26i1SI7PHvVS6B4VF4AhrvGcYgqxTHcjWSQfd6WXttfKICp9ACINguQ6C/pUUctpyevPlhtNaowBm7mnKR8v4XUPYwUjGNPc9ra2+8lOqpX+WLMrHxQf4ELy2G6YTc+p7xaH7dD+bDOvjSlDBF4yMAPj6nsH3xKJSDK7vHhKmJjRp9uzfXkI7J7ALNvK87P73GcfzkF1Y0evp9MCJvDJW458P3j+DwNfnQIhAPdReeIvvvUBTjTGva7yy3UDEuCPqDDEHruxm75bjoxhsUPahJAAB/8NY45hqTaF3Ya2qCRylweSp/kop/uUMbnLPPTfXK8kme46Q7PQMvLcmKhYR85Qpf+65QUQqngE2X2cXh5PrQajdpFOwHt3tLuT9rX3Y4=
    - _R_CHECK_SYSTEM_CLOCK_: false
